version: '3'

services:
  api:
    build: ./api
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000 --reload-dir /usr/src/app
    volumes:
      - ./api:/usr/src/app
    ports:
      - 8004:8000
    restart: on-failure
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_URL=rabbitmq

  pdf_service:
    build: ./pdf_service
    command: python main.py
    restart: on-failure
    volumes:
      - ./pdf_service:/usr/src/app
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_URL=rabbitmq
  
  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15672:15672"
